<?php

function getBrands(){
    return [
        (object)[
            "id" => 1,
            "Marca" => "Café Huila Premium Selection",
            "nombre_corto" => "CafeHuila",
            "País" => "Colombia",
            "Clase" => [30, 43],
            "Estado" => "Registrada",
            "Titular" => "Café del Sur S.A.",
            "Expediente" => "EXP-001",
            "Fecha_Solicitud" => "2023-01-15",
            "Última_Actuación" => "2024-06-20",
            "Tipo" => "Denominativa",
            "icon" => '<i class="fa-duotone fa-light fa-circle-d"></i>',
            "logo" => null,
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Marca que representa café de origen huilense, reconocido por su sabor premium y aroma intenso.",
            "descripcion_abogado" => "Registro consolidado y en plena vigencia. Se recomienda mantener uso constante para evitar caducidad."
        ],
        (object)[
            "id" => 2,
            "Marca" => "Tech Smart Innovators",
            "nombre_corto" => "TechSmart",
            "País" => "México",
            "Clase" => [9, 42],
            "Estado" => "En trámite",
            "Titular" => "Innovaciones Digitales MX",
            "Expediente" => "EXP-002",
            "Fecha_Solicitud" => "2023-03-10",
            "Última_Actuación" => "2024-02-05",
            "Tipo" => "Figurativa",
            "icon" => '<i class="fa-duotone fa-solid fa-images"></i>',
            "logo" => "1.png",
            "company_state" => (object)['id' => 2, 'title' => 'Inactiva', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Desarrolladora de soluciones tecnológicas y software empresarial orientado a la innovación digital.",
            "descripcion_abogado" => "El expediente se encuentra en fase de revisión formal. No se han detectado oposiciones hasta la fecha."
        ],
        (object)[
            "id" => 3,
            "Marca" => "Eco Vida Natural Balance",
            "nombre_corto" => "EcoVida",
            "País" => "Chile",
            "Clase" => [3, 5, 35],
            "Estado" => "Aprobada",
            "Titular" => "Eco Vida Ltda.",
            "Expediente" => "EXP-003",
            "Fecha_Solicitud" => "2023-05-25",
            "Última_Actuación" => "2024-08-12",
            "Tipo" => "Mixta",
            "icon" => '<i class="fa-duotone fa-light fa-circle-m"></i>',
            "logo" => "2.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 2, 'title' => 'Publicada', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "descripcion_comercial" => "Productos de cuidado personal y bienestar con ingredientes 100% naturales.",
            "descripcion_abogado" => "Aprobación otorgada. Pendiente emisión del certificado final de registro."
        ],
        (object)[
            "id" => 4,
            "Marca" => "Agro Finca Export Solutions",
            "nombre_corto" => "AgroFinca",
            "País" => "Perú",
            "Clase" => [1, 31, 44],
            "Estado" => "Rechazada",
            "Titular" => "Agroexport S.A.C.",
            "Expediente" => "EXP-004",
            "Fecha_Solicitud" => "2023-02-18",
            "Última_Actuación" => "2024-05-01",
            "Tipo" => "Denominativa",
            "icon" => '<i class="fa-duotone fa-light fa-circle-d"></i>',
            "logo" => null,
            "company_state" => (object)['id' => 3, 'title' => 'Suspendida', 'description' => 'La empresa fue suspendida temporalmente.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Exportadora de productos agrícolas y soluciones logísticas para el agro.",
            "descripcion_abogado" => "El rechazo se debe a similitud fonética con marca previa. Se recomienda apelación con ajustes de denominación."
        ],
        (object)[
            "id" => 5,
            "Marca" => "Nutri Plus Advanced Nutrition",
            "nombre_corto" => "NutriPlus",
            "País" => "Argentina",
            "Clase" => [5, 29, 32],
            "Estado" => "Registrada",
            "Titular" => "Laboratorios BioPlus",
            "Expediente" => "EXP-005",
            "Fecha_Solicitud" => "2023-07-01",
            "Última_Actuación" => "2024-09-10",
            "Tipo" => "Mixta",
            "icon" => '<i class="fa-duotone fa-light fa-circle-m"></i>',
            "logo" => "3.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Marca de suplementos alimenticios y productos de nutrición avanzada.",
            "descripcion_abogado" => "Registro firme y protegido. Se recomienda extender protección internacional bajo Protocolo de Madrid."
        ],
        (object)[
            "id" => 6,
            "Marca" => "Solar Tech Renewables",
            "nombre_corto" => "SolarTech",
            "País" => "España",
            "Clase" => [9, 11, 37],
            "Estado" => "En revisión",
            "Titular" => "Energías Limpias S.L.",
            "Expediente" => "EXP-006",
            "Fecha_Solicitud" => "2023-09-12",
            "Última_Actuación" => "2024-07-30",
            "Tipo" => "Figurativa",
            "icon" => '<i class="fa-duotone fa-solid fa-images"></i>',
            "logo" => "4.png",
            "company_state" => (object)['id' => 2, 'title' => 'Inactiva', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Empresa dedicada a la fabricación e instalación de paneles solares.",
            "descripcion_abogado" => "En etapa de examen de fondo. Se sugiere monitorear posibles oposiciones por marcas similares."
        ],
        (object)[
            "id" => 7,
            "Marca" => "Vida Fresca Bebidas Naturales",
            "nombre_corto" => "VidaFresca",
            "País" => "Colombia",
            "Clase" => [32, 33],
            "Estado" => "Registrada",
            "Titular" => "Jugos del Campo SAS",
            "Expediente" => "EXP-007",
            "Fecha_Solicitud" => "2023-06-08",
            "Última_Actuación" => "2024-10-01",
            "Tipo" => "Mixta",
            "icon" => '<i class="fa-duotone fa-light fa-circle-m"></i>',
            "logo" => "5.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Marca de jugos naturales y bebidas saludables sin conservantes.",
            "descripcion_abogado" => "Registro consolidado. Recomendado mantener uso comercial activo para evitar cancelación por falta de uso."
        ],
        (object)[
            "id" => 8,
            "Marca" => "Moto Rápido Delivery Service",
            "nombre_corto" => "MotoRapido",
            "País" => "Brasil",
            "Clase" => [12, 39, 42],
            "Estado" => "Pendiente",
            "Titular" => "MotoExpress LTDA",
            "Expediente" => "EXP-008",
            "Fecha_Solicitud" => "2023-04-22",
            "Última_Actuación" => "2024-09-15",
            "Tipo" => "Figurativa",
            "icon" => '<i class="fa-duotone fa-solid fa-images"></i>',
            "logo" => "1.png",
            "company_state" => (object)['id' => 2, 'title' => 'Inactiva', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Servicio de entregas rápidas y mensajería urbana con enfoque tecnológico.",
            "descripcion_abogado" => "Solicitud pendiente de publicación. Se sugiere vigilancia sobre marcas del mismo rubro logístico."
        ],
        (object)[
            "id" => 9,
            "Marca" => "Agua Pura Natural Springs",
            "nombre_corto" => "AguaPura",
            "País" => "Costa Rica",
            "Clase" => [32, 35],
            "Estado" => "Aprobada",
            "Titular" => "Agua Pura Natural CR",
            "Expediente" => "EXP-009",
            "Fecha_Solicitud" => "2023-01-09",
            "Última_Actuación" => "2024-04-02",
            "Tipo" => "Denominativa",
            "icon" => '<i class="fa-duotone fa-light fa-circle-d"></i>',
            "logo" => null,
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 2, 'title' => 'Publicada', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "descripcion_comercial" => "Marca de agua embotellada proveniente de manantiales naturales.",
            "descripcion_abogado" => "Aprobación definitiva otorgada. Pendiente entrega de título oficial del registro."
        ],
        (object)[
            "id" => 10,
            "Marca" => "Fit Zone Active Life",
            "nombre_corto" => "FitZone",
            "País" => "Chile",
            "Clase" => [25, 28, 41],
            "Estado" => "Registrada",
            "Titular" => "Fitness Global SpA",
            "Expediente" => "EXP-010",
            "Fecha_Solicitud" => "2023-05-15",
            "Última_Actuación" => "2024-08-25",
            "Tipo" => "Mixta",
            "icon" => '<i class="fa-duotone fa-light fa-circle-m"></i>',
            "logo" => "2.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Marca dedicada a ropa deportiva y centros de acondicionamiento físico.",
            "descripcion_abogado" => "Registro en orden. Se sugiere protección ampliada en países vecinos por afinidad comercial."
        ],
        (object)[
            "id" => 11,
            "Marca" => "Bio Life Natural Health",
            "nombre_corto" => "BioLife",
            "País" => "Ecuador",
            "Clase" => [5, 35, 44],
            "Estado" => "En trámite",
            "Titular" => "BioLife Ecuador Cía. Ltda.",
            "Expediente" => "EXP-011",
            "Fecha_Solicitud" => "2023-02-28",
            "Última_Actuación" => "2024-07-11",
            "Tipo" => "Denominativa",
            "icon" => '<i class="fa-duotone fa-light fa-circle-d"></i>',
            "logo" => null,
            "company_state" => (object)['id' => 2, 'title' => 'Inactiva', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Marca enfocada en suplementos naturales y bienestar integral.",
            "descripcion_abogado" => "Expediente en análisis. Se recomienda adjuntar evidencia de uso para fortalecer solicitud."
        ],
        (object)[
            "id" => 12,
            "Marca" => "Casa Verde Eco Construction",
            "nombre_corto" => "CasaVerde",
            "País" => "España",
            "Clase" => [19, 37, 42],
            "Estado" => "Registrada",
            "Titular" => "Construcciones Eco S.L.",
            "Expediente" => "EXP-012",
            "Fecha_Solicitud" => "2023-03-14",
            "Última_Actuación" => "2024-10-05",
            "Tipo" => "Figurativa",
            "icon" => '<i class="fa-duotone fa-solid fa-images"></i>',
            "logo" => "3.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Constructora sostenible enfocada en edificaciones ecológicas.",
            "descripcion_abogado" => "Registro firme. Se recomienda incluir eslogan como elemento adicional distintivo."
        ],
        (object)[
            "id" => 13,
            "Marca" => "Andes Cacao Fine Selection",
            "nombre_corto" => "AndesCacao",
            "País" => "Colombia",
            "Clase" => [30, 31, 33],
            "Estado" => "Aprobada",
            "Titular" => "Cacao del Huila SAS",
            "Expediente" => "EXP-013",
            "Fecha_Solicitud" => "2023-06-10",
            "Última_Actuación" => "2024-07-19",
            "Tipo" => "Mixta",
            "icon" => '<i class="fa-duotone fa-light fa-circle-m"></i>',
            "logo" => "4.png",
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 2, 'title' => 'Publicada', 'description' => 'La empresa está registrada pero no realiza operaciones.'],
            "descripcion_comercial" => "Cacao gourmet de alta calidad cultivado en la región andina.",
            "descripcion_abogado" => "Aprobación lista para formalización. Se sugiere registrar diseño gráfico complementario."
        ],
        (object)[
            "id" => 14,
            "Marca" => "GreenFuel Energy Solutions",
            "nombre_corto" => "GreenFuel",
            "País" => "Perú",
            "Clase" => [4, 37, 42],
            "Estado" => "Rechazada",
            "Titular" => "BioEnergy Perú",
            "Expediente" => "EXP-014",
            "Fecha_Solicitud" => "2023-04-04",
            "Última_Actuación" => "2024-06-02",
            "Tipo" => "Figurativa",
            "icon" => '<i class="fa-duotone fa-solid fa-images"></i>',
            "logo" => "5.png",
            "company_state" => (object)['id' => 3, 'title' => 'Suspendida', 'description' => 'La empresa fue suspendida temporalmente.'],
            "entity_state" => (object)['id' => 1, 'title' => 'Presentada', 'description' => 'La empresa está operando normalmente.'],
            "descripcion_comercial" => "Empresa enfocada en combustibles ecológicos y energía verde.",
            "descripcion_abogado" => "Solicitud denegada por coincidencia con marca extranjera. Recomendado presentar recurso de revisión."
        ],
        (object)[
            "id" => 15,
            "Marca" => "Ocean Blue Seafoods",
            "nombre_corto" => "OceanBlue",
            "País" => "Uruguay",
            "Clase" => [29, 31, 35],
            "Estado" => "Registrada",
            "Titular" => "Mar del Sur S.A.",
            "Expediente" => "EXP-015",
            "Fecha_Solicitud" => "2023-05-02",
            "Última_Actuación" => "2024-10-21",
            "Tipo" => "Denominativa",
            "icon" => '<i class="fa-duotone fa-light fa-circle-d"></i>',
            "logo" => null,
            "company_state" => (object)['id' => 1, 'title' => 'Activa', 'description' => 'La empresa está operando normalmente.'],
            "entity_state" => (object)['id' => 3, 'title' => 'Registrada', 'description' => 'La empresa fue suspendida temporalmente.'],
            "descripcion_comercial" => "Distribuidora y procesadora de productos del mar premium.",
            "descripcion_abogado" => "Registro vigente. Se recomienda incluir nuevos logotipos en futuras solicitudes de marca figurativa."
        ],
    ];
}

function getOppositions(){

    return [
        [
            'id' => 1,
            'caso' => 'OP-2025-001',
            "Marca_Referencia" => (object)[
                "id" => 2,
                "nombre_corto" => "TechSmart",
                "Marca" => "Tech Smart Innovators",
                "Expediente" => "EXP-002",
                "Clase" => [9, 42],
            ],
            "Marca_Opositora" => (object)[
                "id" => 6,
                "nombre_corto" => "SolarTech",
                "Marca" => "Solar Tech Renewables",
                "Expediente" => "EXP-006",
                "Clase" => [9, 11, 37],
            ],
            'pais' => 'CO',
            'clase' => 30,
            'tipo_causal' => 'Confusión',
            'estado' => 'En estudio',
            'riesgo' => 'Alto',
            'fecha_limite' => '2025-11-15',
            'abogado_asignado' => 'Laura Gómez',
        ],
        [
            'id' => 2,
            'caso' => 'OP-2025-002',
            "Marca_Referencia" => (object)[
                "id" => 3,
                "nombre_corto" => "EcoVida",
                "Marca" => "Eco Vida Natural Balance",
                "Expediente" => "EXP-003",
                "Clase" => [3, 5, 35],
            ],
            "Marca_Opositora" => (object)[
                "id" => 11,
                "nombre_corto" => "BioLife",
                "Marca" => "Bio Life Natural Health",
                "Expediente" => "EXP-011",
                "Clase" => [5, 35, 44],
            ],
            'pais' => 'CO',
            'clase' => 1,
            'tipo_causal' => 'Absoluta',
            'estado' => 'Activa',
            'riesgo' => 'Medio',
            'fecha_limite' => '2025-11-10',
            'abogado_asignado' => 'Carlos Pérez',
        ],
        [
            'id'    => 3,
            'caso' => 'OP-2025-003',
            "Marca_Referencia" => (object)[
                "id" => 13,
                "nombre_corto" => "AndesCacao",
                "Marca" => "Andes Cacao Fine Selection",
                "Expediente" => "EXP-013",
                "Clase" => [30, 31, 33],
            ],
            "Marca_Opositora" => (object)[
                "id" => 1,
                "nombre_corto" => "CafeHuila",
                "Marca" => "Café Huila Premium Selection",
                "Expediente" => "EXP-001",
                "Clase" => [30, 43],
            ],
            'pais' => 'EC',
            'clase' => 29,
            'tipo_causal' => 'Competencia desleal',
            'estado' => 'Cerrada (favorable)',
            'riesgo' => 'Bajo',
            'fecha_limite' => '2025-09-18',
            'abogado_asignado' => 'Sofía Ruiz',
        ]
    ];
}